apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: uat
  name: mydeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycontainer
        image: nginx:alpine  

        



