apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: web-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: web-data
      persistentVolumeClaim:
        claimName: static-pvc
