apiVersion: v1
kind: Namespace
metadata:
  name: uat  # <-- This is the Namespace (the virtual boundary)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: uat     # Placing this deployment inside the 'uat' namespace
  name: web-app
  labels:
    env: staging     # <-- Label on the Deployment resource itself
    owner: devteam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend  # The selector looks for pods matching this label
  template:
    metadata:
      labels:
        app: frontend # <-- Labels on the individual Pods created by this deployment
        tier: web     # <-- Another label used to categorize these pods
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
