apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-client
  namespace: k8s-services-lab
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: web-demo
  template:
    metadata:
      labels:
        app: web-demo
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine      
