apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
spec:
  nodeSelector:
    lab: troubleshoot
  containers:
    - name: app
      image: nginx:1.27
  tolerations:
  - key: "purpose"
    operator: "Equal"
    value: "special"
    effect: "NoSchedule"    
