apiVersion: v1
kind: Pod
metadata:
  name: grace-pod
spec:
  nodeSelector:
    lab: noexecute-timer
  tolerations:
    - key: "maintenance"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"
      tolerationSeconds: 15
  containers:
    - name: app
      image: nginx:1.27
