apiVersion: v1
kind: Pod
metadata:
  name: wrong-equal
spec:
  nodeSelector:
    lab: operator-demo
  tolerations:
    - key: "team"
      operator: "Equal"
      value: "platform"
      effect: "NoSchedule"
  containers:
    - name: app
      image: nginx:1.27
